[plugin]
repository = "https://github.com/Tischel/ActionTimeline.git"
commit = "6571680df4bb9e8fc0bf7b59d07212d31156fdcc"
owners = ["Tischel"]
project_path = "ActionTimeline"
changelog = "- Fixed windows not being click-through when locked.\n- Fixed Monk's Anatman showing as an oGCD and not triggering the GCD in the timeline.\n- Fixed Ninja's Mudras and Ninjutsus showing as an oGCD and not triggering the GCD in the timeline."