[plugin]
repository = "https://github.com/Tischel/TPie.git"
commit = "e520ca794f198893d293256a9198fea5bdc60feb"
owners = ["Tischel"]
project_path = "TPie"
changelog = "- Added a filter to only show acquired emotes when searching.\n- Fixed some emotes not working."
