[plugin]
repository = "https://github.com/Tischel/TPie.git"
commit = "5e887092d7fffab9c28eb0384a32df03a36afc2c"
owners = ["Tischel"]
project_path = "TPie"
changelog = "- Fixed high quality icons for items."
