[plugin]
repository = "https://github.com/Tischel/TPie.git"
commit = "08215e95392d857ea8d241618937ad3efdd99cf7"
owners = ["Tischel"]
project_path = "TPie"
changelog = "- Fixed TPie not working properly with Penumbra v0.5.8.0 and their new Interface Collection."
