[plugin]
repository = "https://github.com/Tischel/InventorySearchBar.git"
commit = "414bf50aa17b4aa04f265ae9d4bfbf8b4082408c"
owners = ["Tischel"]
project_path = "InventorySearchBar"
changelog = "- Added support for Patch 7.1 and Dalamud API 11."