[plugin]
repository = "https://github.com/Tischel/InventorySearchBar.git"
commit = "a647a9a01ef3bf94d1281141d50755cdf150a59c"
owners = ["Tischel"]
project_path = "InventorySearchBar"
changelog = "- Fixed search bar not being click through when hidden."