[plugin]
repository = "https://github.com/Tischel/InventorySearchBar.git"
commit = "2012de056d3dbad6bfca9da6cf03b0dfa9e3fb6c"
owners = ["Tischel"]
project_path = "InventorySearchBar"
changelog = "- Fixed retainer inventories not working correctly."