[plugin]
repository = "https://github.com/Tischel/InventorySearchBar.git"
commit = "f2f594d0ec7f92833950abc478652edff35f74e9"
owners = ["Tischel"]
project_path = "InventorySearchBar"
changelog = "- Fixed search bar not showing when \"Keybind only\" is disabled."