[plugin]
repository = "https://github.com/Tischel/NOTED.git"
commit = "eb3ed19e21c67b878f04dedce83715668d7a6d12"
owners = ["Tischel"]
project_path = "NOTED"
changelog = "- Fixed note not appearing when creating it inside the duty."