[plugin]
repository = "https://github.com/Tischel/NOTED.git"
commit = "a6f2c27e023e8c897a5a0ac04d2f89404e319506"
owners = ["Tischel"]
project_path = "NOTED"
changelog = "- Removed duplicated duty entries.\n- Added support for the Tab key when writing notes.\n- Fixed visual issues in the settings windows.\n- Fixed crash with notes containing the \"%\" character"